version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
    - 5436:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mapTable
  rso-map:
    image: ls8856/rso-teamlj-map:2.4
    ports:
    - 8084:8084
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5436/mapTable
      KUMULUZEE_DATASOURCES0_USERNAME: dbuser
      KUMULUZEE_DATASOURCES0_PASSWORD: postgres
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
    - postgres
