kumuluzee:
  name: rso-map
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/MapDS
      #connection-url: jdbc:postgresql://localhost/mapTable # TODO - insert correct ip!!
      #username: dbuser
      #password: postgres
      connection-url: jdbc:postgresql://35.228.47.159:5432/mapTable
      username: rso
      password: rso
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: map-endpoint
      url-pattern: /v1/map/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/MapDS
    disk-space-health-check:
      threshold: 100000000
    etcd-health-check:
      connection-url: http://localhost:2379/health
  app-properties:
    external-services:
      enabled: false
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="map">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="5d872f8f-f02a-4f15-b966-e8796ff99a28-ls.logit.io"
                                port="13221" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
