kumuluzee:
  name: rso-map
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  datasources:
    - jndi-name: jdbc/MapDS
      #connection-url: jdbc:postgresql://localhost/mapTable # TODO - insert correct ip!!
      #username: dbuser
      #password: postgres
      connection-url: jdbc:postgresql://192.168.1.5:5436/mapTable # TODO - insert correct ip!!
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: map-endpoint
      url-pattern: /v1/map/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/MapDS
  app-properties:
    external-services:
      enabled: false
