apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
      - name: map
        image: ls8856/rso-teamlj-map:2.2
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: gcloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP
